# vim:ft=yaml.ansible
---

# NOTE:
# * .ssh/config needs an entry with `ForwardAgent yes` for the target host,
#   to pull private git repositories from github.
# * this user needs to be in the hosts sudo group and /etc/sudoers needs to
#   be modified to allow no passwd usage of sudo.

- name: Playbook to set up a new system locally
  hosts: localhost
  gather_facts: true
  vars:
    git_dir: /home/mx/git
  vars_files:
    - ./vars/build_requirements.yml
    - ./vars/keyrings.yml
  pre_tasks:
    - name: Update package cache
      tags: always
      become: true
      ansible.builtin.package:
        update_cache: true
  tasks:
    - name: Core
      ansible.builtin.include_tasks: tasks/core.yml
      tags: core

    # TODO: Copy `eza` from `.cargo/bin` over by hand
    - name: Fish
      ansible.builtin.include_tasks: tasks/fish.yml
      tags: fish
    - name: Nvim
      ansible.builtin.include_tasks: tasks/nvim.yml
      tags: nvim
    # - name: Dotfiles
    #   ansible.builtin.include_tasks: tasks/dotfiles.yml
    #   tags: dotfiles

    # X
    - name: Brave
      ansible.builtin.include_tasks: tasks/brave.yml
      tags: brave
    - name: Syncthing
      ansible.builtin.include_tasks: tasks/syncthing.yml
      tags: syncthing
    - name: Obsidian
      ansible.builtin.include_tasks: tasks/obsidian.yml
      tags: obsidian

    - name: Telegram
      ansible.builtin.include_tasks: tasks/telegram.yml
      tags: telegram

    # NOTE: needs cargo installed to compile alacritty
    - name: Desktop
      ansible.builtin.include_tasks: tasks/desktop.yml
      tags: X

    # TODO:
    # - include: tasks/tor.yml
    # - include: tasks/hacking.yml
    # - include: tasks/mail.yml
    # - include: tasks/nix.yml
    # - include: tasks/docker.yml

    # Old / Unused
    # - include: tasks/ergodox.yml
  #
  handlers:
    - name: Supervisor reload prgrams
      become: true
      community.general.supervisorctl:
        name: "program:"
        state: restarted
