# vim:ft=yaml.ansible
---
- name: Keyring setup
  tags: core
  become: true
  block:
    - name: Add GPG keys
      ansible.builtin.apt_key:
        url: '{{ item.keyfile }}'
        keyring: '{{ item.keyring }}'
      with_items: "{{ keyrings }}"

    - name: Add required apt repository
      ansible.builtin.apt_repository:
        repo: |
          deb [ signed-by={{ item.keyring }} arch=amd64 ] {{ item.repo }}
        state: present
      with_items: "{{ keyrings }}"

    - name: Update package cache
      ansible.builtin.package:
        update_cache: true

# - name: Base packages and tools
#   tags: base
#   vars:
#     packages:
#       - { name: '', key: '' }
#   block:
#     - name:

- name: Create needed directories
  tags: core
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    # - "{{ ansible_env.HOME }}/bin"
    - "{{ git_dir }}"

# - name: Generate locales
#   tags: base
#   block:
#     - name: Copy /etc/locale.gen
#       become: true
#       ansible.builtin.copy:
#         src: locale.gen
#         dest: /etc/locale.gen
#         mode: "0644"
#
#     - name: Run locale-gen
#       become: true
#       ansible.builtin.command: locale-gen
#       register: out
#       changed_when: "'done' in out.stdout"


- name: Install core tools
  become: true
  ansible.builtin.package:
    pkg:
      - git
      - ripgrep
      - fzf
      - tmux
      - direnv
      - gpg
      - btop
      - curl
