# vim:ft=yaml.ansible
---
- name: Keyring setup
  tags: core
  become: true
  block:
    - name: Keyring / Add GPG keys
      ansible.builtin.get_url:
        url: '{{ item.keyfile }}'
        dest: '{{ item.keyring }}'
        mode: 0644
        force: true
      with_items: "{{ keyrings }}"

    - name: Add required apt repository
      ansible.builtin.apt_repository:
        repo: |
          deb [ signed-by={{ item.keyring }} arch=amd64 ] {{ item.repo }}
        state: present
      with_items: "{{ keyrings }}"

    - name: Update package cache
      ansible.builtin.package:
        update_cache: true

- name: Generate /etc/hosts
  tags: core
  become: true
  ansible.builtin.template:
    src: etc_hosts.j2
    dest: /etc/hosts
    mode: 0644

- name: Create needed directories
  tags: core
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    # - "{{ ansible_env.HOME }}/bin"
    - "{{ git_dir }}"

# - name: Generate locales
#   tags: base
#   block:
#     - name: Copy /etc/locale.gen
#       become: true
#       ansible.builtin.copy:
#         src: locale.gen
#         dest: /etc/locale.gen
#         mode: "0644"
#
#     - name: Run locale-gen
#       become: true
#       ansible.builtin.command: locale-gen
#       register: out
#       changed_when: "'done' in out.stdout"

- name: Install core tools
  become: true
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
