# vim:ft=yaml.ansible
---
- name: Remove old Docker versions
  become: true
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  tags:
    - docker

- name: Install the latest version of docker engine
  become: true
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  tags:
    - docker

- name: Enable docker buildkit
  become: true
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "features": {
          "buildkit": true
        }
      }
    mode: 0644
  tags:
    - docker

- name: Add USER to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true
  tags:
    - docker
