# vim:ft=yaml.ansible
---
- name: Fish install
  tags: fish
  become: true
  ansible.builtin.package:
    name:
      - fish
      - zoxide
      - eza
    state: present

- name: Install atuin
  block:
    - name: Fetch setup script
      ansible.builtin.get_url:
        url: https://setup.atuin.sh
        dest: /tmp/setup.atuin.sh
        mode: 0755
      register: atuin_script

    - name: Run setup script
      ansible.builtin.script:
        cmd: /tmp/setup.atuin.sh

    - name: Import fish history
      ansible.builtin.command:
        cmd: "atuin import fish"
      changed_when: true

- name: Make fish the default shell
  tags: fish
  become: true
  ansible.builtin.user:
    name: mx
    shell: /usr/bin/fish

- name: Setup .config/fish
  tags: fish_config
  ansible.builtin.git:
    repo: "git@github.com:mxbl/fish.git"
    dest: "{{ ansible_env.HOME }}/.config/fish"
    update: true
    accept_hostkey: true
    version: main
