# vim:ft=yaml.ansible
---
- name: Download Telegram desktop app
  tags: telegram
  ansible.builtin.unarchive:
    src: https://telegram.org/dl/desktop/linux
    remote_src: true
    dest: /tmp/

- name: Install Telegram to /usr/local/bin
  tags: telegram
  become: true
  ansible.builtin.copy:
    src: /tmp/Telegram/Telegram
    dest: /usr/local/bin/telegram
    mode: "0755"
